### PR TITLE
Remove invisible mounted components from Dropdown

### PR DESCRIPTION
**Pull request by danehansen**
:eyeglasses: @ajacksified & @curioussavage I haven't tested this yet because my shit is broken but just alerting you guys that I have this in the works. It should reduce mounted components on all our dropdown components, which in the case of the home page and subreddit pages, could produce some noticeable savings.

### CODE REVIEW

**Comment by ajacksified** [comment]
@danehansen I also already have this as part of my performance PR.

**Comment by danehansen** [comment]
@ajacksified  This one has less mounted invisible nodes, as well as utilizing react's way of doing this sort transition rather than my old hackey css way.

**Comment by ajacksified** [comment]
Oh, awesome. I'll nuke it from mine after this gets merged in.

**Comment by danehansen** [comment]
@ajacksified or @curioussavage OK this is confirmed working now.

**Comment by ajacksified** [comment]
:fish: 

Some profiling numbers:

Before: ListingDropdown at #1, 6368ms
screen shot 2015-07-09 at 9 45 43 am

After: ListingDropdown at #8, 1142ms
screen shot 2015-07-09 at 9 44 33 am

**Pull request merged**
