### PR TITLE
Submit fixes

### PR DESCRIPTION
**Pull request by curioussavage**
:eyeglasses: @ajacksified

### CODE REVIEW

**Comment by ajacksified** [comment]
:no_bell: lots of `-webkit`-prefixed css; how does this function with opera and firefox mobile?

**Comment by ajacksified** [comment]
:nail_care:

**Comment by curioussavage** [comment]
this looks good on other browsers. From my research it seems android browser is really the only holdout. And even then its just versions prior to 4.4 :haircut:

**Comment by ajacksified** [comment]
:fish:

Jack Lawson
/u/ajacksified <http://reddit.com/u/ajacksified> | @ajacksified
<http://twitter.com/ajacksified> | github/ajacksified
<https://github.com/ajacksified>

**Pull request closed without merging**
