### PR TITLE
Fix mweb bugs, CHAN-354

### PR DESCRIPTION
**Pull request by arjunb023**
Change nav bar position to fixed and update paddings

👓  @wting @prashtx @telaviv

### CODE REVIEW

**Comment by arjunb023** [comment]
Before sort selection fix:
screen shot 2017-02-02 at 3 18 34 pm

After sort selection fix:
screen shot 2017-02-02 at 3 18 23 pm

Relative position nav bar:
screen shot 2017-02-02 at 3 19 43 pm

Fixed position nav bar:
screen shot 2017-02-02 at 3 19 50 pm

**Comment by wting** [comment]
:fish:

**Comment by arjunb023** [comment]
💇

**Comment by wting** [comment]
:running_man: Deferring to @telaviv since this is out of my domain.

**Comment by telaviv** [comment]
💅

**Comment by arjunb023** [comment]
💇

**Comment by telaviv** [comment]
🐟 
```

   ,-----.
  /____  /
 /     \/ _
/ O     \/ |
>          |
\ <)    /\_|
 \_____/\   
  \      \
   `-----'
```

**Comment by arjunb023** [comment]
Merged ac256ec17047255f013ee1b5648b8e84b1539c3b

**Pull request closed without merging**
