### PR TITLE
Nightmode fixes

### PR DESCRIPTION
**Pull request by ajacksified**
All the interstitial changes that went out Wednesday broke a bunch of stuff; here's fixes for the things that were annoying me.

**Before**

screen shot 2016-12-23 at 9 14 53 am

**After**

screen shot 2016-12-23 at 9 17 27 am

btw: NSFW images are still broken because of #931.

Also, that interstitial is the worst thing I have literally ever seen. I'd feel bad for the person who had to write the code to say "my work sucks, use this instead," but good choice having one of the non-core devs do it, eh? But now you've got bugs. _tradeoffs_

### CODE REVIEW

**Comment by ajacksified** [comment]
👓 @telaviv for fixes, @schwers I guess for approval, and maybe @umbrae for a Friday deploy

**Comment by umbrae** [comment]
Thanks for your patch.

Speaking to the rest of it: This isn't acceptable interaction and won't be tolerated. Feel free to email me directly if you would like to discuss.

**Comment by ajacksified** [comment]
Oh also, expanding compact thumbnails is also broken (probably #931 but unconfirmed): check out https://m.reddit.com/r/coolguides on compact.

**Comment by ajacksified** [comment]
Just a gentle ping - nightmode's been broken for over a month now. If I didn't solve the issues in the correct way, or if you have another task or PR or something, feel free to close this instead.

**Comment by salbito** [comment]
bump. In these terrible times I think it is paramount that things work as they should. To enhance the calm of a nation currently under fire.

**Pull request merged**
