### PR TITLE
Shell renderer

### PR DESCRIPTION
**Pull request by ajacksified**
:eyeglasses: @schwers

### CODE REVIEW

**Comment by ajacksified** [comment]
(Rebased on toaster for more user-friendly API-problem error messages.)

**Comment by ajacksified** [comment]
Depends on https://github.com/reddit/node-horse-react/pull/15 and https://github.com/reddit/node-api-client/pull/104

**Comment by ajacksified** [comment]
also 👓 @nramadas

**Comment by schwers** [comment]
:fish:

**Comment by nramadas** [comment]
:fish:

**Pull request merged**
