### PR TITLE
Update "username too short" registration error message

### PR DESCRIPTION
**Pull request by andytuba**
And some incidental grammar cleanup.

https://www.reddit.com/r/bugs/comments/5be1j9/why_does_it_say_too_short_shouldnt_it_say_too_long/

### CODE REVIEW

**Comment by andytuba** [comment]
👓 @scarow @jamesmaa

**Comment by jamesmaa** [comment]
:fish:

**Comment by scarow** [comment]
@andytuba I made a ticket for this!! im trying to find it so i can attach to this PR

**Comment by scarow** [comment]
https://reddit.atlassian.net/browse/CE-600

**Comment by scarow** [comment]
🐟 gr8 grammar

**Comment by andytuba** [comment]
45f450a68434c0758d4cd137b13fd05bf56aa34b...51f3c1e8f1b005d24b834a8ec0645f3b9e13c2d2

**Pull request closed without merging**
