### PR TITLE
Media preview and link behavior changes for post redesign

### PR DESCRIPTION
**Pull request by schwers**
* Depends on some minor nit patches in [524](https://github.com/reddit/reddit-mobile/pull/524/files)
* Pending a small question re: domain vs TLD and prefixless domains for link attribution

### CODE REVIEW

**Comment by schwers** [comment]
:eyeglasses: @curioussavage or @nramadas

**Comment by ajacksified** [comment]
:fish:

**Comment by curioussavage** [comment]
:fish: from me too

**Comment by schwers** [comment]
:haircut: https://github.com/schwers/reddit-mobile/compare/5daa1855fe9d63397f2302383761208b4a425210...ed1ee0d49b43a2bf6a86597f04ffa84e8809a899 If you want to see the new changes since :fish:

**Pull request merged**
