### PR TITLE
Added a link to continue Thread

### PR DESCRIPTION
**Pull request by curioussavage**
this sends the user to the permalink page for the parent comment
so that nesting does not go too deep

see uzis original pr https://github.com/reddit/reddit-mobile/pull/721 for additional insight.

👓 @uzi @schwers

### CODE REVIEW

**Comment by schwers** [comment]
It looks like there's a bug somewhere in applying the '.m-no-indent' class, see this thread for an example: http://localhost:4444/r/AskReddit/comments/2np694/what_tasty_food_would_be_distusting_if_eaten_over/ 

If you find the `Continue this thread` link there will be 4 nested `More Comments` links below that aren't getting `.m-no-indent`

**Comment by schwers** [comment]
Patch makes sense and looks good overall, just a small nit with the indentation 💅

**Comment by curioussavage** [comment]
:haircut_man:

**Comment by schwers** [comment]
:fish:

**Pull request merged**
