### PR TITLE
getExperimentData is safe to call for logged out users.

### PR DESCRIPTION
**Pull request by telaviv**
This is a fix for an error we are seeing in the logs:
```
Feb  6 13:41:08 mweb2x-app-92ebc6a3 [mweb2x] {
  "column": "19", 
  "env": "SERVER", 
  "isAPIFailure": false, 
  "line": "10", 
  "message": "Error: Cannot read property 'features' of undefined", 
  "requestUrl": "/", 
  "stack": "TypeError: Cannot read property 'features' of undefined\n    
at o (/opt/reddit-mobile/bin/webpack:/src/lib/experiments.js:10:19)\n    
at Object.<anonymous> (/opt/reddit-mobile/bin/webpack:/src/app/featureFlags.js:347:26)\n    
at e.a.value (/opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:1876)\n    
at /opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:2060\n    
at Array.some (native)\n    
at /opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:2034\n    
at Array.some (native)\n    
at e.a.value (/opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:1995)\n    
at e.a.value (/opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:1894)\n    
at /opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:2171\n    
at Array.some (native)\n    
at /opt/reddit-mobile/bin/webfepack:/.-deps/@r/flags/flags.js:1:2145\n    
at Array.every (native)\n    
at e.a.value (/opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:2105)\n    
at e.a.value (/opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:1894)\n    
at /opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:2604\n    
at Array.some (native)\n    
at e.a.value (/opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:2578)\n    
at /opt/reddit-mobile/bin/webpack:/src/app/selectors/xpromo.js:44:32\n    
at n (/opt/reddit-mobile/bin/webpack:/.-deps/lodash/_arraySome.js:16:9)\n    
at r (/opt/reddit-mobile/bin/webpack:/.-deps/lodash/some.js:49:10)\n    
at i (/opt/reddit-mobile/bin/webpack:/src/app/selectors/xpromo.js:39:10)\n    
at /opt/reddit-mobile-deps/reselect/lib/index.js:76:27\n    
at Array.map (native)\n    
at selector (/opt/reddit-mobile-deps/reselect/lib/index.js:75:33)\n    
at Connect.configureFinalMapState (/opt/reddit-mobile-deps/react-redux/lib/components/connect.js:154:27)\n    
at Connect.computeStateProps (/opt/reddit-mobile-deps/react-redux/lib/components/connect.js:141:23)\n    
at Connect.updateStatePropsIfNeeded (/opt/reddit-mobile-deps/react-redux/lib/components/connect.js:203:35)\n    
at Connect.render (/opt/reddit-mobile-deps/react-redux/lib/c", 
  "url": "/opt/reddit-mobile/bin/webpack:/src/lib/experiments.js", 
  "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Version/10.0 Mobile/14D27 Safari/602.1"
}
```
👓  @uzi @prashtx

### CODE REVIEW

**Comment by prashtx** [comment]
In what situation is `user` falsey? When we're dealing with a logged out user? In that case, don't we still want the experiment configs, which do still exist for logged-out users?

nit: Can you make sure commit subject is written in the imperative mood? (https://github.com/reddit/styleguide/tree/master/general-style-guidelines#commit-messages)

**Comment by uzi** [comment]
:fish:

**Comment by prashtx** [comment]
💅

**Comment by prashtx** [comment]
Spoke IRL.

:fish: + please update commit message or comments to explain why we might not have a user.

**Pull request merged**
