### PR TITLE
Temporarily remove trending subreddits from search

### PR DESCRIPTION
**Pull request by ajacksified**
:eyeglasses: @jo-asakura

### CODE REVIEW

**Comment by jo-asakura** [comment]
*Temporarily* means you comment it out and bring it back once it's time :smiley: 

:fish:

**Comment by ajacksified** [comment]
@jo-asakura on the contrary, that's what `git revert` is for

**Comment by jo-asakura** [comment]
@ajacksified meh.. too long to type :smile:

**Comment by ajacksified** [comment]
Merged, rebase got borked.

**Pull request closed without merging**
