### PR TITLE
Pass a few more fields to search_events

### PR DESCRIPTION
**Pull request by nramadas**

### CODE REVIEW

**Comment by nramadas** [comment]
@ajacksified :eyeglasses: gracias

**Comment by ajacksified** [comment]
This errors on no referrer - `Cannot read property 'referrer' of undefined`, because `ctx` isn't passed in to `buildPageviewData`. :nail_care:

**Comment by nramadas** [comment]
:haircut:

**Comment by ajacksified** [comment]
:fish:

**Pull request closed without merging**
