### PR TITLE
Cosmetic fixes for Register page

### PR DESCRIPTION
**Pull request by jamesmaa**
Made cosmetic fixes to the Register page.

- Change error tag from <span> to <p>, a block level html tag
- Add `DEFAULT_ERRORS` for handling `errorType` = 'UNKNOWN_ERROR'
- Change default error text to red

👓 : @nramadas

### CODE REVIEW

**Comment by nramadas** [comment]
@jamesmaa quick favor, could you a few screenshots?

**Comment by jamesmaa** [comment]
Yep!
image
image
image

**Comment by nramadas** [comment]
Thanks! While we're in there, can we add two more cosmetic changes?

0. There seems to be an extra line between "Choose a unique username" and "Choose a unique password". Let's get rid of one of the lines
0. Let's add some spacing between the checkbox and "Subscribe to newsletter". Maybe 4px or so?
0. Also with the checkbox, it doesn't seem to be vertically aligned with the text. Can we try adjusting the line-height, or giving both a `diplay: inline-block; vertical-align: middle;` treatment?

**Comment by jamesmaa** [comment]
`top` seems more vertically aligned than `middle`
image
image

**Comment by nramadas** [comment]
:fish:

**Pull request merged**
