### PR TITLE
Polish stuff

### PR DESCRIPTION
**Pull request by jo-asakura**
:eyeglasses: @ajacksified or @danehansen 

```
* Upvote /downvote circles are smaller on comments
* Meta-data text on posts, such as timestamp, is too lightly colored (ios)
* Background color on activated posts is colored too lightly (ios)
* Name of logged-in user shouldn't disappear from menu when viewing their profile
* Timestamps for comments should be aligned right, before comment score, rather than on the left
```

### CODE REVIEW

**Comment by ajacksified** [comment]
Timestamps and karma are broken:

screen shot 2015-04-20 at 11 34 25 am

**Comment by jo-asakura** [comment]
Is it some specific case? I see this:

**Comment by ajacksified** [comment]
Nah, I messed something up on my end. :fish:

**Comment by jo-asakura** [comment]
:cool:

**Comment by ajacksified** [comment]
poland

**Comment by jo-asakura** [comment]
lol

**Pull request closed without merging**
