### PR TITLE
[inline @r/redux-state-archiver] Reduce the size of reduxe-state-arch…

### PR DESCRIPTION
**Pull request by curioussavage**
…iver by inlining it

Same as the other inling commits
  * 859KB         -> 857KB
  * 224KB gzipped -> 223KB gzipped

### CODE REVIEW

**Comment by curioussavage** [comment]
👓  @curioussavage @schwers 

is the commit message fine as is?

**Comment by curioussavage** [comment]
🐟  

For history: not my pull request - cherry-picked in order to review/merge faster

**Comment by madbook** [comment]
@curioussavage I'd recommend reformatting that commit message – it doesn't really follow our commit message style (too long, bracketed prefix is not something we normally do)

**Comment by madbook** [comment]
also, there is a typo (`reduxe` vs `redux`)

**Comment by madbook** [comment]
also, why are we doing this? Is there a jira ticket or something you can link to?

**Comment by curioussavage** [comment]
@madbook  yeah. sorry I jumped the gun with the fish. There will be some changes to the commit message. I will rebase this after ryan merges in his commits that add a bundle analyzer. I need to redo the analysis to update the change in size.

ticket is here: https://reddit.atlassian.net/browse/CONT-163

**Comment by curioussavage** [comment]
:haircut_man:

**Pull request merged**
