### PR TITLE
Rename front page to home

### PR DESCRIPTION
**Pull request by luisatlive**
@nramadas this will be part of https://reddit.atlassian.net/browse/HOT-127 so will need some handholding on deploy once we're ready to make the change, I believe Jonathan is targeting Monday?

Also, my first actual PR so I'm sure I screwed up process somewhere, feel free to nitpick :)

:eyeglasses:

### CODE REVIEW

**Comment by nramadas** [comment]
:fish:

**Comment by prashtx** [comment]
nit: commit subject should be declarative ("Rename front page to home and remove All")

since you asked ; )

**Comment by luisatlive** [comment]
Fixed :)

**Comment by prashtx** [comment]
:fish:

**Comment by luisatlive** [comment]
:eyeglasses: @nramadas @prashtx direction changed again, no longer removing r/all, just renaming Front Page to Home now.

**Comment by prashtx** [comment]
:fish:

**Comment by luisatlive** [comment]
Closing since I didn't fork the branch (which I will next time)

**Pull request closed without merging**
