### PR TITLE
Interstitials

### PR DESCRIPTION
**Pull request by curioussavage**
:eyeglasses: @ajacksified 

depends on https://github.com/reddit/snoode/pull/48

### CODE REVIEW

**Comment by ajacksified** [comment]
Server flashes interstitial if you're logged in, with over_18 true, and before you get the cookie set.

I see two options:

* Add bypass code like:
```
let bypassInterstitial = data.userPrefs && data.userPrefs.over_18;
if (!bypassInterstitial) {
  if (data.subreddits && data.subreddits.over18 && props.showOver18Interstitial) { 
    <Interstitial>
  }
}
```

* Add a post-data-load modifyContext to horse-react on the server, so that you can set `ctx.props.showOver18Interstitial` after the prefs have loaded.

The second is more complicated, but we should keep an eye out to places where we have to hack around not having the data loaded on the server at prop-setting time. The first should be good enough to get this out.

:nail_care:

**Comment by curioussavage** [comment]
:haircut: 

ok going with the first option for now.

**Comment by ajacksified** [comment]
:fish:

**Comment by curioussavage** [comment]
interstitial-over18

**Comment by curioussavage** [comment]
:eyeglasses: @tdohz & @spez since this is user facing.

**Comment by spez** [comment]
:fish:

**Comment by tdohz** [comment]
@librarianavenger for a quick design review but LGTM!

Erica, if you want to check on staging: https://www.cloudflarestagingformobilereddit.com/r/gonewilder (actually SFW)

**Comment by librarianavenger** [comment]
looks good on desktop - 18+ image and style don't appear on chrome mobile - might just be a staging thing? either way, yay.

**Comment by ajacksified** [comment]
I see it on chrome mobile (android), fwiw.

**Comment by curioussavage** [comment]
so I'm assuming its fine to push this out?...

**Comment by librarianavenger** [comment]
fine with me!

**Comment by librarianavenger** [comment]
weirdly, still seeing this on desktop when not logged in 
screen shot 2015-10-19 at 3 41 41 pm

**Comment by ajacksified** [comment]
@librarianavenger it isn't live yet

**Comment by librarianavenger** [comment]
NEVER MIND

**Comment by ajacksified** [comment]
@librarianavenger now you can try :D

**Pull request closed without merging**
