### PR TITLE
make the logged out redirect location a constant

### PR DESCRIPTION
**Pull request by phil303**
Since this may change in the future, making it a constant will make it
easier to do updates.

:eyeglasses: @schwers

### CODE REVIEW

**Comment by schwers** [comment]
Nice! Can you swap the `'/login'` in `handlers/Vote.js` too? 💅

**Comment by phil303** [comment]
woops, missed one, yes.

**Comment by phil303** [comment]
:haircut:

**Comment by schwers** [comment]
:fish:

**Pull request merged**
