### PR TITLE
Merge pull request #116 from danehansen/compact_view

### PR DESCRIPTION
**Pull request by danehansen**
Implement compact view

:eyeglasses: @ajacksified

### CODE REVIEW

**Comment by ajacksified** [comment]
All looks good, although the background to the subnav is dark instead of white:

screen shot 2015-05-01 at 2 14 34 pm

**Comment by danehansen** [comment]
@ajacksified  yea its supposed to be

**Comment by ajacksified** [comment]
Oh, ok; I thought the designs had it in white. :fish:

**Comment by danehansen** [comment]
yea for the design its actually the lower lighter blue, but since that wouldn't provide contrast against the profile page i left it a shade darker, same color as the previous nav bar.

**Pull request merged**
