### PR TITLE
Fix PR #944

### PR DESCRIPTION
**Pull request by ajacksified**
Fixes a typo on pr #944, which turns the background instead of the text color. Whoops, sorry >.<

👓  @fruchtose

### CODE REVIEW

**Comment by fruchtose** [comment]
Thanks for the fix. I noticed the bug and aborted deploying it.

**Comment by ajacksified** [comment]
👍

**Comment by ajacksified** [comment]
While I've got your ear, @fruchtose, do you know if the non-sticky header is intentional or if it's also a bug? I know it was changed at the same time as the new interstitials, but wasn't sure if it was to fix a bug with interstitials or removed for other reasons. I miss it, because navigating between subs is just a little more annoying now; I typically want to switch subreddits at the bottom of a page, which means hiking back up to the top.

**Comment by fruchtose** [comment]
Hmmm, I'll look into it.

**Comment by fruchtose** [comment]
@ajacksified unfortunately I found out that the sticky nav isn't ready at this point due to what I believe is an interstitial compatibility problem.

**Comment by ajacksified** [comment]
Figured as much. Thanks for looking into it!

**Pull request merged**
