### PR TITLE
Remove overflow:hidden so subreddit search works

### PR DESCRIPTION
**Pull request by ajacksified**
:eyeglasses: @curioussavage - do you know why this was set to hidden? Search is broken right now (you can't scroll) without this set to visible. Seems fine without overflow:hidden.

### CODE REVIEW

**Comment by curioussavage** [comment]
lgtm, having the scrollbar is much better than not being able to scroll.

:fish:

**Comment by curioussavage** [comment]
actually if you increase the height on `.sub-selection-selected` by a pixel or two it no longer scrolls. looks like its content is slightly overflowing

**Comment by curioussavage** [comment]
@ajacksified It has to be at least 50px

**Comment by ajacksified** [comment]
closed for https://github.com/reddit/reddit-mobile/pull/450

**Pull request closed without merging**
