### PR TITLE
Comment: remove 'more from' from comment menu

### PR DESCRIPTION
**Pull request by curioussavage**
:eyeglasses: @madbook 

low hanging fruit. 

https://reddit.atlassian.net/browse/MOBILEWEB-134

### CODE REVIEW

**Comment by ajacksified** [comment]
Would it be better to pass subreddit in, than to hide it if it doesn't exist?

**Comment by ajacksified** [comment]
:nail_care:

**Comment by curioussavage** [comment]
I figured this was better because you have many other links to the subreddit on the detail page, so it seemed redundant to have a link to the sub in every single comments menu. thoughts?  :haircut:

**Comment by ajacksified** [comment]
Sure, :fish:

**Comment by madbook** [comment]
gah, I had a whole thing written out but you two are two fast.  Code looks good :fish:

**Pull request merged**
