### PR TITLE
Handle recaptcha component unmounting before a promise resolves

### PR DESCRIPTION
**Pull request by curioussavage**
👓  @jackniu1 @schwers 

https://sentry.reddit.ue1.snooguts.net/sentry/mobile-web/issues/4440/

Looks like people are leaving the page before the promise resolves. I followed the suggestion here https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html for the fix.

### CODE REVIEW

**Comment by jackniu1** [comment]
Could an extra `onloadCallback` resolve this? Following `https://github.com/appleboy/react-recaptcha/issues/181` (sorry for the bug introduced at first place!).

**Comment by curioussavage** [comment]
Doesn't look like it. They are doing a different but kind similar thing. their component works differently but they still have a `componentWillUnmount` to destroy their timer that checks if its loaded every second.

**Comment by curioussavage** [comment]
:haircut_man:

**Comment by jackniu1** [comment]
🐟

**Pull request closed without merging**
