### PR TITLE
Change Post tool display

### PR DESCRIPTION
**Pull request by scarow**
Previously, we were using a tooltip to show
actions like save, report, etc. We are moving
towards a new design that utilizes modals
instead, to make it easier to implement mod
tools with updated design in the future.

screen shot 2016-12-13 at 2 24 51 pm
screen shot 2016-12-13 at 2 24 37 pm

https://reddit.atlassian.net/browse/CE-353

### CODE REVIEW

**Comment by scarow** [comment]
👓 @birakattack @nramadas

**Comment by powerlanguage** [comment]
@scarow can we remove the horizontal lines per the designs attached to https://reddit.atlassian.net/browse/CE-353 ?

**Comment by scarow** [comment]
@powerlanguage oh yeah! good eye

**Comment by scarow** [comment]
For comments:
screen shot 2016-12-13 at 3 02 03 pm

**Comment by scarow** [comment]
@birakattack in subsequent patches, I'll probably move this into its own component so we can dispatch API calls from the component itself.

**Comment by nramadas** [comment]
this is an annoying question: should there be an explicit "close" call to action in the modal somewhere? on small screens (and especially when we add a few more options for mod actions), there might not be enough of the black overlay visible for the modal to be easily closed.

**Comment by powerlanguage** [comment]
@nramadas I think this is a good suggestion, but outside the scope of the current work.  I'll file a separate ticket for this task.

**Comment by birakattack** [comment]
:fish: lgtm

**Pull request merged**
