### PR TITLE
Fix nsfw blueness

### PR DESCRIPTION
**Pull request by ajacksified**
Grey:

screen shot 2015-06-11 at 9 41 20 am

Instead of blue:

screen shot 2015-06-11 at 9 42 24 am

cc @danehansen and @limmmster

### CODE REVIEW

**Comment by limmmster** [comment]
lgtm

**Comment by danehansen** [comment]
it was blue in .psd jennifer gave me

**Comment by ajacksified** [comment]
Oh. I'll hold until @boriss says otherwise.

**Comment by Boriss** [comment]
It’s covered in a level of black at 10% opacity.  If the image is blue, it'll look a big blue.  More importantly, you should always be able to see the white letters.

**Pull request closed without merging**
