### PR TITLE
Facets

### PR DESCRIPTION
**Pull request by curioussavage**
:eyeglasses:  @ajacksified 

Everybody seemed to be ok with how search was when I showed it, so here is this pr with working subreddit search. 

Will want some help to separate out the requests, I think I could do most of it myself making sure the url and server rendering stuff all works fine is mostly what I'm not sure about. So maybe Ill start a new branch?

https://github.com/reddit/snoode/pull/20

### CODE REVIEW

**Comment by ajacksified** [comment]
Sure - so this to turn off facets, then another pass to break it into two separate requests?

:fish:

**Comment by curioussavage** [comment]
yes. turn off facets and add the type param so we get subreddits back too.

**Comment by ajacksified** [comment]
(merged)

**Comment by curioussavage** [comment]
5a23020d74f3637ba7ae2362ae0852eac36307ee

**Pull request closed without merging**
