### PR TITLE
Add VCL rule to redirect users based on user agent and cookie. (CHAN-48)

### PR DESCRIPTION
**Pull request by wting**
We redirect users to mweb if we detect a mobile or tablet user agent string,
and if the override cookie is not present. All other users will be redirected
to the desktop site.

:eyeglasses: @gtaylor @kjoconnor 

cc: @prashtx @KeyserSosa

### CODE REVIEW

**Comment by kjoconnor** [comment]
Ricky's out this week FYI, so I can review this

**Comment by kjoconnor** [comment]
A couple things here - we probably want to split this into two commits (and possibly two PRs) as you're adding redirects but also adding a whole testing suite (thanks!). You probably also want @KeyserSosa on here. Let me know if you'd like to continue this in one big chunk or split it up.

Thanks!

💅

**Comment by wting** [comment]
@kjoconnor: Thanks for catching the PTO and offering to review.

I've separated the PR into two commits.

The current acceptance testing suite is a temp replacement. I imagine the final acceptance test suite (CHAN-131) will be JavaScript-based and involve spinning up and tearing down containers.

I found it useful to have automated tests rather than manually testing user agent strings and cookies myself, but am OK with dropping the testing stuff from the PR.

:haircut:

**Comment by kjoconnor** [comment]
cool, lgtm! thanks! 🐟

**Pull request closed without merging**
