### PR TITLE
Don't display scores that are hidden

### PR DESCRIPTION
**Pull request by dwick**
I was primarily concerned with ads always showing 0 due to being heavily downvoted, but figured we might as well hit all the cases .com does.

Here's some screenshots:

screen shot 2015-07-28 at 11 42 21 am
screen shot 2015-07-28 at 11 51 39 am

:eyeglasses: @danehansen @limmmster

### CODE REVIEW

**Comment by dwick** [comment]
related: https://github.com/reddit/reddit-public/pull/3965

**Comment by danehansen** [comment]
should we just leave out the voting buttons and score altogether? seems better to me than to have pointless vote buttons and "score hidden" text. @limmmster @dwick

**Comment by dwick** [comment]
@danehansen just because you dont see the score doesn't mean there isn't one and votes still do matter internally.  also, sometimes scores are only hidden for a period of time.

**Comment by danehansen** [comment]
:fish:

**Comment by dwick** [comment]
https://github.com/reddit/reddit-mobile/commit/fc1c91be9fc53d64c3a877a8298f2b1be3639efb

**Pull request closed without merging**
