### PR TITLE
Make community header banner render at 10:3

### PR DESCRIPTION
**Pull request by schwers**
https://reddit.atlassian.net/browse/MOBILEWEB-374

### CODE REVIEW

**Comment by schwers** [comment]
:eyeglasses: @curioussavage or @nramadas or @ajacksified

**Comment by curioussavage** [comment]
:fish: lgtm

**Comment by tdohz** [comment]
Please hold on pushing so we can coordinate with the settings change.

**Comment by schwers** [comment]
Will do

**Comment by ajacksified** [comment]
inb4 complaints about the header taking up too much space :fish:

**Comment by schwers** [comment]
Using `needs_design_review` as a indicator that we're holding for coordination and will double check with design before launch

**Pull request merged**
