### PR TITLE
ListingContent: remove display of images linked to in urls of link posts

### PR DESCRIPTION
**Pull request by curioussavage**
:eyeglasses: @ajacksified @umbrae

### CODE REVIEW

**Comment by umbrae** [comment]
:fish: This all looks right to me, but I'm pretty newbish in the mweb space so we might want to wait for @ajacksified to take a look.

**Comment by ajacksified** [comment]
:fish:

**Comment by ajacksified** [comment]
@curioussavage - NSFW thumbnails no longer appear in compact mode (just the blue image with "NSFW"), and in list view, it's always embedded (rather than the pixelated view.)

:nail_care:

**Comment by ajacksified** [comment]
Nevermind, that's an existing regression. :fish:

**Pull request closed without merging**
