### PR TITLE
Add .ackrc

### PR DESCRIPTION
**Pull request by uzi**
Ack is a useful find/grep sort of utility. It can
help folks understand out codebase quicker.  This
hides generated files from searches to make things
friendlier.

👓  @schwers @phil303 @nramadas

### CODE REVIEW

**Comment by phil303** [comment]
I think all we need is `bin` and `build`. `node_modules` I ack from time to time, `.test` should be getting deleted after tests are run I believe - if not, there's a bug, and .git should never be a problem.

**Comment by phil303** [comment]
:nail_care:

**Comment by schwers** [comment]
I'm actually in favor of having `.test` explicitly ignored. The likelihood of it popping up is exceptionally rare, but it seems good to rule out this potential source of confusion.

**Comment by schwers** [comment]
💅

**Comment by uzi** [comment]
If you want to search node_modules, you can just `cd` into it.

**Comment by uzi** [comment]
💇 I took out the `.git` directory but left `node_modules` in.  The reason is my use case is that I don't want to search `node_modules` unless I explicitly intend to, which can be done by `cd`ing into it.

**Comment by phil303** [comment]
ok sounds reasonable to me :fish:

**Pull request merged**
