### PR TITLE
GTM: Set frame name properly

### PR DESCRIPTION
**Pull request by dwick**
👓 @schwers 

regression from https://github.com/reddit/reddit-mobile/commit/a70f8757b026879e27119ebad22b2410e7867c12

### CODE REVIEW

**Comment by schwers** [comment]
:fish:

**Comment by phil303** [comment]
@dwick. What end effect does this patch have and can you add that to the commit description?

**Comment by phil303** [comment]
:nail_care: for more commit description please

**Comment by dwick** [comment]
💇 can one of you deploy this if it's good?

**Comment by phil303** [comment]
:fish: I got it! Thanks for the fix!!

cc @umbrae

**Pull request merged**
