### PR TITLE
Update nightmode icon to spaceship

### PR DESCRIPTION
**Pull request by schwers**
image

image

### CODE REVIEW

**Comment by curioussavage** [comment]
I like it

**Comment by schwers** [comment]
:eyeglasses: @curioussavage

**Comment by ajacksified** [comment]
I liked the yellow sun for daymode :(

Spaceship is awesome though.

**Comment by curioussavage** [comment]
:fish:  lgtm

**Comment by schwers** [comment]
I liked the yellow as well, maybe in the future we can do a half sun / half moon thing

**Pull request merged**
