### PR TITLE
Add `sandbox` attribute to off-site iframes

### PR DESCRIPTION
**Pull request by JordanMilne**
:eyeglasses: @ajacksified 

Prevents framed sites from busting the frame or opening popups, like we do in https://github.com/reddit/reddit/blob/master/r2/r2/templates/innertoolbarframe.html#L42

### CODE REVIEW

**Comment by ajacksified** [comment]
:fish:

**Comment by umbrae** [comment]
Can you hold on pushing this? I'd like to review (I seem to recall some big
issues when I've used sandbox before)

**Comment by umbrae** [comment]
Oh wait, this was for mobile! Nevermind!

**Comment by ajacksified** [comment]
:+1:

**Pull request merged**
