### PR TITLE
add visual studio code files to gitignore

### PR DESCRIPTION
**Pull request by curioussavage**
:eyeglasses: @schwers 

cc @ajacksified and @nramadas 

any other stuff that should be in here?

### CODE REVIEW

**Comment by ajacksified** [comment]
:fish:

**Comment by spladug** [comment]
unsolicited but fwiw, I don't think IDE-specific stuff should be in a project's gitignore. You should configure your personal environment (via global gitignore) for any IDEs you use and projects should only have the stuff that's relevant to that project. Otherwise you'll end up with everyone's laundry list of editors in your gitignore which isn't really that great in the long run.

**Comment by curioussavage** [comment]
^ this is a great point. I think this should be closed in favor of spladug's suggestion.

**Comment by schwers** [comment]
@curioussavage I agree. I didn't realize there was a global config; that seems like the perfect place for this kind of stuff

**Comment by curioussavage** [comment]
ok, closing.

**Comment by ajacksified** [comment]
Fair  enough. My idea was it lowers the barrier slightly for open source
prs, but yeah, could get messy fast.

**Pull request closed without merging**
