### PR TITLE
Switch Drone/kage to Quay.io.

### PR DESCRIPTION
**Pull request by gtaylor**
Now that we've got legal approval to do, we're moving our Docker images over to Quay.io. This PR adjusts .drone.yml to push to Quay, and .kage to pull from there.

:eyeglasses: @nramadas @spladug @ckwang8128

### CODE REVIEW

**Comment by spladug** [comment]
:fish:

**Comment by ckwang8128** [comment]
:fish:

**Comment by gtaylor** [comment]
Merged in e5eb68d1c19e09010b7099b9b15c0c03198e27de

**Comment by gtaylor** [comment]
Merged in fc8a2e14000411bdde3f45a812285ce23a023cd7

**Pull request closed without merging**
