### PR TITLE
Support Blocks

### PR DESCRIPTION
**Pull request by schwers**
Depends on https://github.com/reddit/snoode/pull/98

### CODE REVIEW

**Comment by schwers** [comment]
There's some tricky/hacking manipulation of <Comment />'s state because of how replies are loaded in, that part could use some extra thoughtful review. I think it's a good example of why we should continue considering redux as then we'd have better access to the full comment tree

**Comment by schwers** [comment]
:eyeglasses: @ajacksified @nramadas

**Comment by schwers** [comment]
We should add blocks in 2X soon, it's probably okay to keep this open for reference's sake, but we don't need it yet

**Comment by phil303** [comment]
@schwers can we kill this?

**Comment by schwers** [comment]
@phil303 I'm going to close it for now, I'll make sure there's a ticket for this

**Pull request closed without merging**
