### PR TITLE
Move aspect ratios from JavaScript to CSS for list view

### PR DESCRIPTION
**Pull request by danehansen**
:eyeglasses: @ajacksified or @curioussavage

### CODE REVIEW

**Comment by danehansen** [comment]
HTF does this have zero files changed?

**Comment by ajacksified** [comment]
Expand content is broken (/r/gifs/comments/39a3se/one_of_the_largest_great_whites_ever_filmed/ for example); image previews look good.

:nail_care:

**Comment by limmmster** [comment]
excited for this.

**Comment by danehansen** [comment]
:haircut: @ajacksified

**Comment by ajacksified** [comment]
:fish:

**Pull request merged**
