### PR TITLE
Fix galleries, and imgur that look like galleries or jpg

### PR DESCRIPTION
**Pull request by schwers**
[example of a gif that plays correctly now because of posing like a gallery link](https://m.reddit.com/r/HighQualityGifs/comments/45esfv/what_the_hobbit_needed_was_more_fx/)

### CODE REVIEW

**Comment by schwers** [comment]
:eyeglasses: @curioussavage or @ajacksified

**Comment by ajacksified** [comment]
Semi-related: some urls (m.reddit.com/r/HighQualityGifs/comments/462kk5/when_i_saw_google_fiber_trucks_burying_lines_by/) don't get rid of the play icon.

Unrelated: it's super annoying that embedly seems to be random on what it turns into a gallery (like m.reddit.com/r/DIY/comments/45wt6c/i_found_a_pair_of_hifi_speakers_at_the_side_of/ doesn't have the embed data.)

Seems fine otherwise; probably want to take care of that first issue in a separate PR? If so, :fish:

**Comment by curioussavage** [comment]
:fish: from me 2

**Comment by schwers** [comment]
Ya I'll address the first part in separate pr. I think to really fix it I'll need to get a pause icon and some design input on where to put it. But maybe its just better to not show the play icon at all _and_ no pause for now

**Comment by schwers** [comment]
Also yes, that gallery example is really odd. Just from the url its obviously a gallery.

**Comment by ajacksified** [comment]
:fish:

**Pull request merged**
